stages:
  - test
  - deploy

default:
  tags:
    - kubos

.build_bbb: &build_bbb
  script:
    - ./build.sh | tee full_build.log
  artifacts:
    name: '$KUBOS_BOARD'
    paths:
      - output/kubos-linux.tar.gz
      - output/aux-sd.tar.gz
      - output/kpack-kubos.itb
      - full_build.log

build_mbm2:
  variables:
    KUBOS_BOARD: pumpkin-mbm2
  <<: *build_bbb

# do a release when both kubos and kubos-linux-build are tagged
release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'release job'
  release:
    name: 'Release $KUBOS_TAG-$CI_COMMIT_TAG'
    tag_name: '$KUBOS_TAG-$CI_COMMIT_TAG'
    description: 'kubos source $KUBOS_TAG built against kubos-linux-build $CI_COMMIT_TAG'
  rules:
    - if: $KUBOS_TAG =~ /^[0-9]+(\.[0-9]+)*$/ && $CI_COMMIT_TAG =~ /^[0-9]+(\.[0-9]+)*$/
